<a href="https://colab.research.google.com/github/soyoonjeong/PyTorch_Tutorial/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

## 텐서 초기화

In [ ]:
# 데이터로부터 직접 생성하기 => torch.tensor
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [ ]:
# numpy 배열로부터 생성하기 => torch.from_numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
# 다른 텐서로부터 생성하기 (다른 텐서의 모양과 자료형 유지)
x_ones = torch.ones_like(x_data) # x_data의 속성 유지, 1로 채워진, 입력 텐서와 동일한 모양의 텐서
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # x_data의 속성을 덮어씀, 랜덤 수로 채워진, 입력 텐서와 동일한 모양의 텐서
print(f"Random Tensor : \n {x_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.5341, 0.8577],
        [0.2100, 0.5859]]) 



In [ ]:
# 무작위 또는 상수 값을 사용하기
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f"Zeros Tensor : \n {zeros_tensor} \n")

Random Tensor : 
 tensor([[0.2673, 0.7112, 0.4666],
        [0.2437, 0.3558, 0.3080]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 텐서의 속성

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor : {tensor.shape}") # 모양
print(f"Datatype of tensor : {tensor.dtype}") # 자료형
print(f"Device tensor is stored on : {tensor.device}") # 어느 장치에 저장되는지

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


## 텐서 연산

In [ ]:
# GPU의 가용성을 확인한 뒤 GPU로 텐서를 명시적으로 이동
# 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 든다
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [ ]:
# NumPy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4,4)
print(f"First row : {tensor[0]}")
print(f"First column : {tensor[:, 0]}")
print(f"Last column : {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
# 산술 연산

# 행렬 곱
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3)

# 요소별 곱 (element-wise product)
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
# 단일 요소 텐서
agg = tensor.sum()
agg_item = agg.item() # 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서인 경우, item()을 사용하여 숫자 값으로 변환할 수 있음
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
# 바꿔치기 연산 : 연산 결과를 피연산자에 저장하는 연산
# 바꿔치기 연산은 메모리를 일부 절약하지만 기록이 즉시 삭제되어 도함수 계산에 문제가 발생할 수 있음
# 바꿔치기 연산은 되도록 사용하지 말것
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환

In [ ]:
# 텐서를 NumPy 배열로 변환하기
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [ ]:
# CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.
# 텐서의 변경 사항이 NumPy 배열에 반영됩니다.
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


In [ ]:
# NumPy 배열을 텐서로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n : [1. 1. 1. 1. 1.]


In [ ]:
# NumPy 배열의 변경사항이 텐서에 반영됩니다.
np.add(n, 1, out = n)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
